package fr.miage.millan.feuxcarrefourihm.objetsGraphiques;

import fr.miage.millan.feuxcarrefourihm.librairiesExternes.RoundedPanel;
import java.awt.Color;

/**
 *Un jPanel qui représente une ampoule d'un feu de circulation
 * 
 * @author aympa
 */
public class Ampoule extends RoundedPanel {

    /**
     * Constructeur de l'ampoule
     */
    public Ampoule() {
        initComponents();
        this.couleurAmpouleEteinte = Color.GRAY;
    }      
    
    //Méthodes
    /**
     * Permet d'allumer ou d'éteindre l'ampoule du feu de circulation
     * @param allumerAmpoule Positionner à true si on veut allumer l'ampoule, false si on veut l'éteindre
     */
    public void allume(boolean allumerAmpoule){
        if(allumerAmpoule){
            this.setBackground(this.couleurDeFeu);
        }
        else{
            this.setBackground(this.couleurAmpouleEteinte);
        }
    }  
        
    //Getters
    /**
     * Pour modifier la couleur de l'ampoule
     * @param couleur la couleur qu'on veut assigner à l'ampoule
     */
    public void setCouleurDeFeu(Color couleur){
        this.couleurDeFeu = couleur;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    //Attributs
    /**
     * La couleur de l'ampoule 
     */
    private Color couleurDeFeu;
    /**
     * La couleur lorsque l'ampoule est éteinte (Gris ou noir en général)
     * Pour pouvoir modifier en fonction du fond de la Frame sur laquelle on utilise l'ampoule
     */
    private final Color couleurAmpouleEteinte;    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
