package fr.miage.millan.feuxcarrefourihm.objetsGraphiques;

import java.awt.Color;

/**
 * Un BlocFeux réprésente trois panels Ampoule avec chacun une couleur (Rouge, Vert, Orange)
 *
 * @author aympa
 */
public class BlocFeux extends javax.swing.JPanel {

    /**
     * Constructeur et initialisation du panel
     */
    public BlocFeux() {
        initComponents();
        
        //Mise en place des couleurs des trois ampoules du feu
        this.panelAmpouleRouge.setCouleurDeFeu(Color.RED);
        this.panelAmpouleOrange.setCouleurDeFeu(Color.ORANGE);
        this.panelAmpouleVert.setCouleurDeFeu(Color.GREEN);
    }

    //Méthodes
    /**
     * Eteint les trois panelAmpoule du feu
     */
    public void eteindTout(){
        this.panelAmpouleRouge.allume(false);
        this.panelAmpouleOrange.allume(false);
        this.panelAmpouleVert.allume(false);
    }
    
    /**
     * Allume le panelAmpouleRouge et éteint les autres
     */
    public void allumeSeulementRouge(){
        this.panelAmpouleRouge.allume(true);
        this.panelAmpouleOrange.allume(false);
        this.panelAmpouleVert.allume(false);
    }
    
    /**
     * Allume le panelAmpouleVert et éteint les autres
     */
    public void allumeSeulementVert(){
        this.panelAmpouleRouge.allume(false);
        this.panelAmpouleOrange.allume(false);
        this.panelAmpouleVert.allume(true);
    }
    
    /**
     * Allume le panelAmpouleOrange et éteint les autres
     */
    public void allumeSeulementOrange(){
        this.panelAmpouleRouge.allume(false);
        this.panelAmpouleOrange.allume(true);
        this.panelAmpouleVert.allume(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAmpouleRouge = new fr.miage.millan.feuxcarrefourihm.objetsGraphiques.Ampoule();
        panelAmpouleOrange = new fr.miage.millan.feuxcarrefourihm.objetsGraphiques.Ampoule();
        panelAmpouleVert = new fr.miage.millan.feuxcarrefourihm.objetsGraphiques.Ampoule();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setOpaque(false);
        setLayout(new java.awt.GridLayout(3, 1, 5, 1));

        javax.swing.GroupLayout panelAmpouleRougeLayout = new javax.swing.GroupLayout(panelAmpouleRouge);
        panelAmpouleRouge.setLayout(panelAmpouleRougeLayout);
        panelAmpouleRougeLayout.setHorizontalGroup(
            panelAmpouleRougeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );
        panelAmpouleRougeLayout.setVerticalGroup(
            panelAmpouleRougeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        add(panelAmpouleRouge);

        javax.swing.GroupLayout panelAmpouleOrangeLayout = new javax.swing.GroupLayout(panelAmpouleOrange);
        panelAmpouleOrange.setLayout(panelAmpouleOrangeLayout);
        panelAmpouleOrangeLayout.setHorizontalGroup(
            panelAmpouleOrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );
        panelAmpouleOrangeLayout.setVerticalGroup(
            panelAmpouleOrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        add(panelAmpouleOrange);

        javax.swing.GroupLayout panelAmpouleVertLayout = new javax.swing.GroupLayout(panelAmpouleVert);
        panelAmpouleVert.setLayout(panelAmpouleVertLayout);
        panelAmpouleVertLayout.setHorizontalGroup(
            panelAmpouleVertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );
        panelAmpouleVertLayout.setVerticalGroup(
            panelAmpouleVertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        add(panelAmpouleVert);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fr.miage.millan.feuxcarrefourihm.objetsGraphiques.Ampoule panelAmpouleOrange;
    private fr.miage.millan.feuxcarrefourihm.objetsGraphiques.Ampoule panelAmpouleRouge;
    private fr.miage.millan.feuxcarrefourihm.objetsGraphiques.Ampoule panelAmpouleVert;
    // End of variables declaration//GEN-END:variables
}
